<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ChangelogFile>$(MSBuildThisFileDirectory)/../../CHANGELOG.md</ChangelogFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Commander.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Glutinum.Converter\Glutinum.Converter.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EasyBuild.PackageReleaseNotes.Tasks">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Glutinum.Node" />
  </ItemGroup>
</Project>
