<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Prelude.fs" />
    <Compile Include="Utils/String.fs" />
    <Compile Include="Utils/Keywords.fs" />
    <Compile Include="Utils/Naming.fs" />
    <Compile Include="Utils/List.fs" />
    <Compile Include="Log.fs" />
    <Compile Include="TypeScript.fs" />
    <Compile Include="TypeScript.Extensions.fs" />
    <Compile Include="TsMorph.fs" />
    <Compile Include="GlueAST.fs" />
    <Compile Include="Reader/Report.fs" />
    <Compile Include="Reader/Types.fs" />
    <Compile Include="Reader/Utils.fs" />
    <Compile Include="Reader/ClassDeclaration.fs" />
    <Compile Include="Reader/EnumDeclaration.fs" />
    <Compile Include="Reader/FunctionDeclaration.fs" />
    <Compile Include="Reader/IndexedAccessType.fs" />
    <Compile Include="Reader/InterfaceDeclaration.fs" />
    <Compile Include="Reader/ModuleDeclaration.fs" />
    <Compile Include="Reader/Declaration.fs" />
    <Compile Include="Reader/Node.fs" />
    <Compile Include="Reader/Parameters.fs" />
    <Compile Include="Reader/TypeAliasDeclaration.fs" />
    <Compile Include="Reader/TypeQueryNode.fs" />
    <Compile Include="Reader/TypeNode.fs" />
    <Compile Include="Reader/TypeOperatorNode.fs" />
    <Compile Include="Reader/TypeParameters.fs" />
    <Compile Include="Reader/UnionTypeNode.fs" />
    <Compile Include="Reader/MappedTypeNode.fs" />
    <Compile Include="Reader/VariableStatement.fs" />
    <Compile Include="Reader/ExportAssignment.fs" />
    <Compile Include="Reader/ExportDeclaration.fs" />
    <Compile Include="Reader/Documentation.fs" />
    <Compile Include="Reader/NamedTupleMember.fs" />
    <Compile Include="Reader/TypeScriptReader.fs" />
    <Compile Include="FsharpAST.fs" />
    <Compile Include="Read.fs" />
    <Compile Include="Merge.fs" />
    <Compile Include="Abbreviations.fs" />
    <Compile Include="Transformer/Comment.fs" />
    <Compile Include="Transformer/TypeParameters.fs" />
    <Compile Include="Transformer/Heritage.fs" />
    <Compile Include="Transformer/Utils.fs" />
    <Compile Include="Transformer/ParamObjectCandidate.fs" />
    <Compile Include="Transformer/UnionOverloads.fs" />
    <Compile Include="Transformer/AnyFunctionOverloads.fs" />
    <Compile Include="Transformer/Conditionals.fs" />
    <Compile Include="Transformer/CallableProperties.fs" />
    <Compile Include="Transformer/Enum.fs" />
    <Compile Include="Transformer/KeyOfMaps.fs" />
    <Compile Include="Transformer/Context.fs" />
    <Compile Include="FreeTypeParameters.fs" />
    <Compile Include="DelegateExtensions.fs" />
    <Compile Include="Transform.fs" />
    <Compile Include="Printer.fs" />
    <Compile Include="Hosting.fs" />
    <Compile Include="Packages.fs" />
    <Compile Include="Generate.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Promise" />
    <PackageReference Include="FSToolkit.ErrorHandling" />
    <PackageReference Include="Glutinum.Chalk" />
    <PackageReference Include="Glutinum.Node" />
    <PackageReference Include="Glutinum.Types" />
  </ItemGroup>
</Project>
