module TypeScriptHelpers

module SyntaxKind =
    open TypeScript.Ts

    let name =
        function
        | SyntaxKind.Unknown -> "Unknown"
        | SyntaxKind.EndOfFileToken -> "EndOfFileToken"
        | SyntaxKind.SingleLineCommentTrivia -> "SingleLineCommentTrivia"
        | SyntaxKind.MultiLineCommentTrivia -> "MultiLineCommentTrivia"
        | SyntaxKind.NewLineTrivia -> "NewLineTrivia"
        | SyntaxKind.WhitespaceTrivia -> "WhitespaceTrivia"
        | SyntaxKind.ShebangTrivia -> "ShebangTrivia"
        | SyntaxKind.ConflictMarkerTrivia -> "ConflictMarkerTrivia"
        | SyntaxKind.NonTextFileMarkerTrivia -> "NonTextFileMarkerTrivia"
        | SyntaxKind.NumericLiteral -> "NumericLiteral"
        | SyntaxKind.BigIntLiteral -> "BigIntLiteral"
        | SyntaxKind.StringLiteral -> "StringLiteral"
        | SyntaxKind.JsxText -> "JsxText"
        | SyntaxKind.JsxTextAllWhiteSpaces -> "JsxTextAllWhiteSpaces"
        | SyntaxKind.RegularExpressionLiteral -> "RegularExpressionLiteral"
        | SyntaxKind.NoSubstitutionTemplateLiteral ->
            "NoSubstitutionTemplateLiteral"
        | SyntaxKind.TemplateHead -> "TemplateHead"
        | SyntaxKind.TemplateMiddle -> "TemplateMiddle"
        | SyntaxKind.TemplateTail -> "TemplateTail"
        | SyntaxKind.OpenBraceToken -> "OpenBraceToken"
        | SyntaxKind.CloseBraceToken -> "CloseBraceToken"
        | SyntaxKind.OpenParenToken -> "OpenParenToken"
        | SyntaxKind.CloseParenToken -> "CloseParenToken"
        | SyntaxKind.OpenBracketToken -> "OpenBracketToken"
        | SyntaxKind.CloseBracketToken -> "CloseBracketToken"
        | SyntaxKind.DotToken -> "DotToken"
        | SyntaxKind.DotDotDotToken -> "DotDotDotToken"
        | SyntaxKind.SemicolonToken -> "SemicolonToken"
        | SyntaxKind.CommaToken -> "CommaToken"
        | SyntaxKind.QuestionDotToken -> "QuestionDotToken"
        | SyntaxKind.LessThanToken -> "LessThanToken"
        | SyntaxKind.LessThanSlashToken -> "LessThanSlashToken"
        | SyntaxKind.GreaterThanToken -> "GreaterThanToken"
        | SyntaxKind.LessThanEqualsToken -> "LessThanEqualsToken"
        | SyntaxKind.GreaterThanEqualsToken -> "GreaterThanEqualsToken"
        | SyntaxKind.EqualsEqualsToken -> "EqualsEqualsToken"
        | SyntaxKind.ExclamationEqualsToken -> "ExclamationEqualsToken"
        | SyntaxKind.EqualsEqualsEqualsToken -> "EqualsEqualsEqualsToken"
        | SyntaxKind.ExclamationEqualsEqualsToken ->
            "ExclamationEqualsEqualsToken"
        | SyntaxKind.EqualsGreaterThanToken -> "EqualsGreaterThanToken"
        | SyntaxKind.PlusToken -> "PlusToken"
        | SyntaxKind.MinusToken -> "MinusToken"
        | SyntaxKind.AsteriskToken -> "AsteriskToken"
        | SyntaxKind.AsteriskAsteriskToken -> "AsteriskAsteriskToken"
        | SyntaxKind.SlashToken -> "SlashToken"
        | SyntaxKind.PercentToken -> "PercentToken"
        | SyntaxKind.PlusPlusToken -> "PlusPlusToken"
        | SyntaxKind.MinusMinusToken -> "MinusMinusToken"
        | SyntaxKind.LessThanLessThanToken -> "LessThanLessThanToken"
        | SyntaxKind.GreaterThanGreaterThanToken ->
            "GreaterThanGreaterThanToken"
        | SyntaxKind.GreaterThanGreaterThanGreaterThanToken ->
            "GreaterThanGreaterThanGreaterThanToken"
        | SyntaxKind.AmpersandToken -> "AmpersandToken"
        | SyntaxKind.BarToken -> "BarToken"
        | SyntaxKind.CaretToken -> "CaretToken"
        | SyntaxKind.ExclamationToken -> "ExclamationToken"
        | SyntaxKind.TildeToken -> "TildeToken"
        | SyntaxKind.AmpersandAmpersandToken -> "AmpersandAmpersandToken"
        | SyntaxKind.BarBarToken -> "BarBarToken"
        | SyntaxKind.QuestionToken -> "QuestionToken"
        | SyntaxKind.ColonToken -> "ColonToken"
        | SyntaxKind.AtToken -> "AtToken"
        | SyntaxKind.QuestionQuestionToken -> "QuestionQuestionToken"
        //SyntaxKind./ -> "/"
        | SyntaxKind.BacktickToken -> "BacktickToken"
        //SyntaxKind./ -> "/"
        | SyntaxKind.HashToken -> "HashToken"
        | SyntaxKind.EqualsToken -> "EqualsToken"
        | SyntaxKind.PlusEqualsToken -> "PlusEqualsToken"
        | SyntaxKind.MinusEqualsToken -> "MinusEqualsToken"
        | SyntaxKind.AsteriskEqualsToken -> "AsteriskEqualsToken"
        | SyntaxKind.AsteriskAsteriskEqualsToken ->
            "AsteriskAsteriskEqualsToken"
        | SyntaxKind.SlashEqualsToken -> "SlashEqualsToken"
        | SyntaxKind.PercentEqualsToken -> "PercentEqualsToken"
        | SyntaxKind.LessThanLessThanEqualsToken ->
            "LessThanLessThanEqualsToken"
        | SyntaxKind.GreaterThanGreaterThanEqualsToken ->
            "GreaterThanGreaterThanEqualsToken"
        | SyntaxKind.GreaterThanGreaterThanGreaterThanEqualsToken ->
            "GreaterThanGreaterThanGreaterThanEqualsToken"
        | SyntaxKind.AmpersandEqualsToken -> "AmpersandEqualsToken"
        | SyntaxKind.BarEqualsToken -> "BarEqualsToken"
        | SyntaxKind.BarBarEqualsToken -> "BarBarEqualsToken"
        | SyntaxKind.AmpersandAmpersandEqualsToken ->
            "AmpersandAmpersandEqualsToken"
        | SyntaxKind.QuestionQuestionEqualsToken ->
            "QuestionQuestionEqualsToken"
        | SyntaxKind.CaretEqualsToken -> "CaretEqualsToken"
        | SyntaxKind.Identifier -> "Identifier"
        | SyntaxKind.PrivateIdentifier -> "PrivateIdentifier"
        | SyntaxKind.BreakKeyword -> "BreakKeyword"
        | SyntaxKind.CaseKeyword -> "CaseKeyword"
        | SyntaxKind.CatchKeyword -> "CatchKeyword"
        | SyntaxKind.ClassKeyword -> "ClassKeyword"
        | SyntaxKind.ConstKeyword -> "ConstKeyword"
        | SyntaxKind.ContinueKeyword -> "ContinueKeyword"
        | SyntaxKind.DebuggerKeyword -> "DebuggerKeyword"
        | SyntaxKind.DefaultKeyword -> "DefaultKeyword"
        | SyntaxKind.DeleteKeyword -> "DeleteKeyword"
        | SyntaxKind.DoKeyword -> "DoKeyword"
        | SyntaxKind.ElseKeyword -> "ElseKeyword"
        | SyntaxKind.EnumKeyword -> "EnumKeyword"
        | SyntaxKind.ExportKeyword -> "ExportKeyword"
        | SyntaxKind.ExtendsKeyword -> "ExtendsKeyword"
        | SyntaxKind.FalseKeyword -> "FalseKeyword"
        | SyntaxKind.FinallyKeyword -> "FinallyKeyword"
        | SyntaxKind.ForKeyword -> "ForKeyword"
        | SyntaxKind.FunctionKeyword -> "FunctionKeyword"
        | SyntaxKind.IfKeyword -> "IfKeyword"
        | SyntaxKind.ImportKeyword -> "ImportKeyword"
        | SyntaxKind.InKeyword -> "InKeyword"
        | SyntaxKind.InstanceOfKeyword -> "InstanceOfKeyword"
        | SyntaxKind.NewKeyword -> "NewKeyword"
        | SyntaxKind.NullKeyword -> "NullKeyword"
        | SyntaxKind.ReturnKeyword -> "ReturnKeyword"
        | SyntaxKind.SuperKeyword -> "SuperKeyword"
        | SyntaxKind.SwitchKeyword -> "SwitchKeyword"
        | SyntaxKind.ThisKeyword -> "ThisKeyword"
        | SyntaxKind.ThrowKeyword -> "ThrowKeyword"
        | SyntaxKind.TrueKeyword -> "TrueKeyword"
        | SyntaxKind.TryKeyword -> "TryKeyword"
        | SyntaxKind.TypeOfKeyword -> "TypeOfKeyword"
        | SyntaxKind.VarKeyword -> "VarKeyword"
        | SyntaxKind.VoidKeyword -> "VoidKeyword"
        | SyntaxKind.WhileKeyword -> "WhileKeyword"
        | SyntaxKind.WithKeyword -> "WithKeyword"
        | SyntaxKind.ImplementsKeyword -> "ImplementsKeyword"
        | SyntaxKind.InterfaceKeyword -> "InterfaceKeyword"
        | SyntaxKind.LetKeyword -> "LetKeyword"
        | SyntaxKind.PackageKeyword -> "PackageKeyword"
        | SyntaxKind.PrivateKeyword -> "PrivateKeyword"
        | SyntaxKind.ProtectedKeyword -> "ProtectedKeyword"
        | SyntaxKind.PublicKeyword -> "PublicKeyword"
        | SyntaxKind.StaticKeyword -> "StaticKeyword"
        | SyntaxKind.YieldKeyword -> "YieldKeyword"
        | SyntaxKind.AbstractKeyword -> "AbstractKeyword"
        | SyntaxKind.AccessorKeyword -> "AccessorKeyword"
        | SyntaxKind.AsKeyword -> "AsKeyword"
        | SyntaxKind.AssertsKeyword -> "AssertsKeyword"
        | SyntaxKind.AssertKeyword -> "AssertKeyword"
        | SyntaxKind.AnyKeyword -> "AnyKeyword"
        | SyntaxKind.AsyncKeyword -> "AsyncKeyword"
        | SyntaxKind.AwaitKeyword -> "AwaitKeyword"
        | SyntaxKind.BooleanKeyword -> "BooleanKeyword"
        | SyntaxKind.ConstructorKeyword -> "ConstructorKeyword"
        | SyntaxKind.DeclareKeyword -> "DeclareKeyword"
        | SyntaxKind.GetKeyword -> "GetKeyword"
        | SyntaxKind.InferKeyword -> "InferKeyword"
        | SyntaxKind.IntrinsicKeyword -> "IntrinsicKeyword"
        | SyntaxKind.IsKeyword -> "IsKeyword"
        | SyntaxKind.KeyOfKeyword -> "KeyOfKeyword"
        | SyntaxKind.ModuleKeyword -> "ModuleKeyword"
        | SyntaxKind.NamespaceKeyword -> "NamespaceKeyword"
        | SyntaxKind.NeverKeyword -> "NeverKeyword"
        | SyntaxKind.OutKeyword -> "OutKeyword"
        | SyntaxKind.ReadonlyKeyword -> "ReadonlyKeyword"
        | SyntaxKind.RequireKeyword -> "RequireKeyword"
        | SyntaxKind.NumberKeyword -> "NumberKeyword"
        | SyntaxKind.ObjectKeyword -> "ObjectKeyword"
        | SyntaxKind.SatisfiesKeyword -> "SatisfiesKeyword"
        | SyntaxKind.SetKeyword -> "SetKeyword"
        | SyntaxKind.StringKeyword -> "StringKeyword"
        | SyntaxKind.SymbolKeyword -> "SymbolKeyword"
        | SyntaxKind.TypeKeyword -> "TypeKeyword"
        | SyntaxKind.UndefinedKeyword -> "UndefinedKeyword"
        | SyntaxKind.UniqueKeyword -> "UniqueKeyword"
        | SyntaxKind.UnknownKeyword -> "UnknownKeyword"
        | SyntaxKind.UsingKeyword -> "UsingKeyword"
        | SyntaxKind.FromKeyword -> "FromKeyword"
        | SyntaxKind.GlobalKeyword -> "GlobalKeyword"
        | SyntaxKind.BigIntKeyword -> "BigIntKeyword"
        | SyntaxKind.OverrideKeyword -> "OverrideKeyword"
        | SyntaxKind.OfKeyword -> "OfKeyword"
        | SyntaxKind.QualifiedName -> "QualifiedName"
        | SyntaxKind.ComputedPropertyName -> "ComputedPropertyName"
        | SyntaxKind.TypeParameter -> "TypeParameter"
        | SyntaxKind.Parameter -> "Parameter"
        | SyntaxKind.Decorator -> "Decorator"
        | SyntaxKind.PropertySignature -> "PropertySignature"
        | SyntaxKind.PropertyDeclaration -> "PropertyDeclaration"
        | SyntaxKind.MethodSignature -> "MethodSignature"
        | SyntaxKind.MethodDeclaration -> "MethodDeclaration"
        | SyntaxKind.ClassStaticBlockDeclaration ->
            "ClassStaticBlockDeclaration"
        | SyntaxKind.Constructor -> "Constructor"
        | SyntaxKind.GetAccessor -> "GetAccessor"
        | SyntaxKind.SetAccessor -> "SetAccessor"
        | SyntaxKind.CallSignature -> "CallSignature"
        | SyntaxKind.ConstructSignature -> "ConstructSignature"
        | SyntaxKind.IndexSignature -> "IndexSignature"
        | SyntaxKind.TypePredicate -> "TypePredicate"
        | SyntaxKind.TypeReference -> "TypeReference"
        | SyntaxKind.FunctionType -> "FunctionType"
        | SyntaxKind.ConstructorType -> "ConstructorType"
        | SyntaxKind.TypeQuery -> "TypeQuery"
        | SyntaxKind.TypeLiteral -> "TypeLiteral"
        | SyntaxKind.ArrayType -> "ArrayType"
        | SyntaxKind.TupleType -> "TupleType"
        | SyntaxKind.OptionalType -> "OptionalType"
        | SyntaxKind.RestType -> "RestType"
        | SyntaxKind.UnionType -> "UnionType"
        | SyntaxKind.IntersectionType -> "IntersectionType"
        | SyntaxKind.ConditionalType -> "ConditionalType"
        | SyntaxKind.InferType -> "InferType"
        | SyntaxKind.ParenthesizedType -> "ParenthesizedType"
        | SyntaxKind.ThisType -> "ThisType"
        | SyntaxKind.TypeOperator -> "TypeOperator"
        | SyntaxKind.IndexedAccessType -> "IndexedAccessType"
        | SyntaxKind.MappedType -> "MappedType"
        | SyntaxKind.LiteralType -> "LiteralType"
        | SyntaxKind.NamedTupleMember -> "NamedTupleMember"
        | SyntaxKind.TemplateLiteralType -> "TemplateLiteralType"
        | SyntaxKind.TemplateLiteralTypeSpan -> "TemplateLiteralTypeSpan"
        | SyntaxKind.ImportType -> "ImportType"
        | SyntaxKind.ObjectBindingPattern -> "ObjectBindingPattern"
        | SyntaxKind.ArrayBindingPattern -> "ArrayBindingPattern"
        | SyntaxKind.BindingElement -> "BindingElement"
        | SyntaxKind.ArrayLiteralExpression -> "ArrayLiteralExpression"
        | SyntaxKind.ObjectLiteralExpression -> "ObjectLiteralExpression"
        | SyntaxKind.PropertyAccessExpression -> "PropertyAccessExpression"
        | SyntaxKind.ElementAccessExpression -> "ElementAccessExpression"
        | SyntaxKind.CallExpression -> "CallExpression"
        | SyntaxKind.NewExpression -> "NewExpression"
        | SyntaxKind.TaggedTemplateExpression -> "TaggedTemplateExpression"
        | SyntaxKind.TypeAssertionExpression -> "TypeAssertionExpression"
        | SyntaxKind.ParenthesizedExpression -> "ParenthesizedExpression"
        | SyntaxKind.FunctionExpression -> "FunctionExpression"
        | SyntaxKind.ArrowFunction -> "ArrowFunction"
        | SyntaxKind.DeleteExpression -> "DeleteExpression"
        | SyntaxKind.TypeOfExpression -> "TypeOfExpression"
        | SyntaxKind.VoidExpression -> "VoidExpression"
        | SyntaxKind.AwaitExpression -> "AwaitExpression"
        | SyntaxKind.PrefixUnaryExpression -> "PrefixUnaryExpression"
        | SyntaxKind.PostfixUnaryExpression -> "PostfixUnaryExpression"
        | SyntaxKind.BinaryExpression -> "BinaryExpression"
        | SyntaxKind.ConditionalExpression -> "ConditionalExpression"
        | SyntaxKind.TemplateExpression -> "TemplateExpression"
        | SyntaxKind.YieldExpression -> "YieldExpression"
        | SyntaxKind.SpreadElement -> "SpreadElement"
        | SyntaxKind.ClassExpression -> "ClassExpression"
        | SyntaxKind.OmittedExpression -> "OmittedExpression"
        | SyntaxKind.ExpressionWithTypeArguments ->
            "ExpressionWithTypeArguments"
        | SyntaxKind.AsExpression -> "AsExpression"
        | SyntaxKind.NonNullExpression -> "NonNullExpression"
        | SyntaxKind.MetaProperty -> "MetaProperty"
        | SyntaxKind.SyntheticExpression -> "SyntheticExpression"
        | SyntaxKind.SatisfiesExpression -> "SatisfiesExpression"
        | SyntaxKind.TemplateSpan -> "TemplateSpan"
        | SyntaxKind.SemicolonClassElement -> "SemicolonClassElement"
        | SyntaxKind.Block -> "Block"
        | SyntaxKind.EmptyStatement -> "EmptyStatement"
        | SyntaxKind.VariableStatement -> "VariableStatement"
        | SyntaxKind.ExpressionStatement -> "ExpressionStatement"
        | SyntaxKind.IfStatement -> "IfStatement"
        | SyntaxKind.DoStatement -> "DoStatement"
        | SyntaxKind.WhileStatement -> "WhileStatement"
        | SyntaxKind.ForStatement -> "ForStatement"
        | SyntaxKind.ForInStatement -> "ForInStatement"
        | SyntaxKind.ForOfStatement -> "ForOfStatement"
        | SyntaxKind.ContinueStatement -> "ContinueStatement"
        | SyntaxKind.BreakStatement -> "BreakStatement"
        | SyntaxKind.ReturnStatement -> "ReturnStatement"
        | SyntaxKind.WithStatement -> "WithStatement"
        | SyntaxKind.SwitchStatement -> "SwitchStatement"
        | SyntaxKind.LabeledStatement -> "LabeledStatement"
        | SyntaxKind.ThrowStatement -> "ThrowStatement"
        | SyntaxKind.TryStatement -> "TryStatement"
        | SyntaxKind.DebuggerStatement -> "DebuggerStatement"
        | SyntaxKind.VariableDeclaration -> "VariableDeclaration"
        | SyntaxKind.VariableDeclarationList -> "VariableDeclarationList"
        | SyntaxKind.FunctionDeclaration -> "FunctionDeclaration"
        | SyntaxKind.ClassDeclaration -> "ClassDeclaration"
        | SyntaxKind.InterfaceDeclaration -> "InterfaceDeclaration"
        | SyntaxKind.TypeAliasDeclaration -> "TypeAliasDeclaration"
        | SyntaxKind.EnumDeclaration -> "EnumDeclaration"
        | SyntaxKind.ModuleDeclaration -> "ModuleDeclaration"
        | SyntaxKind.ModuleBlock -> "ModuleBlock"
        | SyntaxKind.CaseBlock -> "CaseBlock"
        | SyntaxKind.NamespaceExportDeclaration -> "NamespaceExportDeclaration"
        | SyntaxKind.ImportEqualsDeclaration -> "ImportEqualsDeclaration"
        | SyntaxKind.ImportDeclaration -> "ImportDeclaration"
        | SyntaxKind.ImportClause -> "ImportClause"
        | SyntaxKind.NamespaceImport -> "NamespaceImport"
        | SyntaxKind.NamedImports -> "NamedImports"
        | SyntaxKind.ImportSpecifier -> "ImportSpecifier"
        | SyntaxKind.ExportAssignment -> "ExportAssignment"
        | SyntaxKind.ExportDeclaration -> "ExportDeclaration"
        | SyntaxKind.NamedExports -> "NamedExports"
        | SyntaxKind.NamespaceExport -> "NamespaceExport"
        | SyntaxKind.ExportSpecifier -> "ExportSpecifier"
        | SyntaxKind.MissingDeclaration -> "MissingDeclaration"
        | SyntaxKind.ExternalModuleReference -> "ExternalModuleReference"
        | SyntaxKind.JsxElement -> "JsxElement"
        | SyntaxKind.JsxSelfClosingElement -> "JsxSelfClosingElement"
        | SyntaxKind.JsxOpeningElement -> "JsxOpeningElement"
        | SyntaxKind.JsxClosingElement -> "JsxClosingElement"
        | SyntaxKind.JsxFragment -> "JsxFragment"
        | SyntaxKind.JsxOpeningFragment -> "JsxOpeningFragment"
        | SyntaxKind.JsxClosingFragment -> "JsxClosingFragment"
        | SyntaxKind.JsxAttribute -> "JsxAttribute"
        | SyntaxKind.JsxAttributes -> "JsxAttributes"
        | SyntaxKind.JsxSpreadAttribute -> "JsxSpreadAttribute"
        | SyntaxKind.JsxExpression -> "JsxExpression"
        | SyntaxKind.JsxNamespacedName -> "JsxNamespacedName"
        | SyntaxKind.CaseClause -> "CaseClause"
        | SyntaxKind.DefaultClause -> "DefaultClause"
        | SyntaxKind.HeritageClause -> "HeritageClause"
        | SyntaxKind.CatchClause -> "CatchClause"
        | SyntaxKind.AssertClause -> "AssertClause"
        | SyntaxKind.AssertEntry -> "AssertEntry"
        | SyntaxKind.ImportTypeAssertionContainer ->
            "ImportTypeAssertionContainer"
        | SyntaxKind.PropertyAssignment -> "PropertyAssignment"
        | SyntaxKind.ShorthandPropertyAssignment ->
            "ShorthandPropertyAssignment"
        | SyntaxKind.SpreadAssignment -> "SpreadAssignment"
        | SyntaxKind.EnumMember -> "EnumMember"
        //SyntaxKind./ -> "/"
        | SyntaxKind.UnparsedPrologue -> "UnparsedPrologue"
        //SyntaxKind./ -> "/"
        | SyntaxKind.UnparsedPrepend -> "UnparsedPrepend"
        //SyntaxKind./ -> "/"
        | SyntaxKind.UnparsedText -> "UnparsedText"
        //SyntaxKind./ -> "/"
        | SyntaxKind.UnparsedInternalText -> "UnparsedInternalText"
        //SyntaxKind./ -> "/"
        | SyntaxKind.UnparsedSyntheticReference -> "UnparsedSyntheticReference"
        | SyntaxKind.SourceFile -> "SourceFile"
        | SyntaxKind.Bundle -> "Bundle"
        //SyntaxKind./ -> "/"
        | SyntaxKind.UnparsedSource -> "UnparsedSource"
        //SyntaxKind./ -> "/"
        | SyntaxKind.InputFiles -> "InputFiles"
        | SyntaxKind.JSDocTypeExpression -> "JSDocTypeExpression"
        | SyntaxKind.JSDocNameReference -> "JSDocNameReference"
        | SyntaxKind.JSDocMemberName -> "JSDocMemberName"
        | SyntaxKind.JSDocAllType -> "JSDocAllType"
        | SyntaxKind.JSDocUnknownType -> "JSDocUnknownType"
        | SyntaxKind.JSDocNullableType -> "JSDocNullableType"
        | SyntaxKind.JSDocNonNullableType -> "JSDocNonNullableType"
        | SyntaxKind.JSDocOptionalType -> "JSDocOptionalType"
        | SyntaxKind.JSDocFunctionType -> "JSDocFunctionType"
        | SyntaxKind.JSDocVariadicType -> "JSDocVariadicType"
        | SyntaxKind.JSDocNamepathType -> "JSDocNamepathType"
        | SyntaxKind.JSDoc -> "JSDoc"
        | SyntaxKind.JSDocText -> "JSDocText"
        | SyntaxKind.JSDocTypeLiteral -> "JSDocTypeLiteral"
        | SyntaxKind.JSDocSignature -> "JSDocSignature"
        | SyntaxKind.JSDocLink -> "JSDocLink"
        | SyntaxKind.JSDocLinkCode -> "JSDocLinkCode"
        | SyntaxKind.JSDocLinkPlain -> "JSDocLinkPlain"
        | SyntaxKind.JSDocTag -> "JSDocTag"
        | SyntaxKind.JSDocAugmentsTag -> "JSDocAugmentsTag"
        | SyntaxKind.JSDocImplementsTag -> "JSDocImplementsTag"
        | SyntaxKind.JSDocAuthorTag -> "JSDocAuthorTag"
        | SyntaxKind.JSDocDeprecatedTag -> "JSDocDeprecatedTag"
        | SyntaxKind.JSDocClassTag -> "JSDocClassTag"
        | SyntaxKind.JSDocPublicTag -> "JSDocPublicTag"
        | SyntaxKind.JSDocPrivateTag -> "JSDocPrivateTag"
        | SyntaxKind.JSDocProtectedTag -> "JSDocProtectedTag"
        | SyntaxKind.JSDocReadonlyTag -> "JSDocReadonlyTag"
        | SyntaxKind.JSDocOverrideTag -> "JSDocOverrideTag"
        | SyntaxKind.JSDocCallbackTag -> "JSDocCallbackTag"
        | SyntaxKind.JSDocOverloadTag -> "JSDocOverloadTag"
        | SyntaxKind.JSDocEnumTag -> "JSDocEnumTag"
        | SyntaxKind.JSDocParameterTag -> "JSDocParameterTag"
        | SyntaxKind.JSDocReturnTag -> "JSDocReturnTag"
        | SyntaxKind.JSDocThisTag -> "JSDocThisTag"
        | SyntaxKind.JSDocTypeTag -> "JSDocTypeTag"
        | SyntaxKind.JSDocTemplateTag -> "JSDocTemplateTag"
        | SyntaxKind.JSDocTypedefTag -> "JSDocTypedefTag"
        | SyntaxKind.JSDocSeeTag -> "JSDocSeeTag"
        | SyntaxKind.JSDocPropertyTag -> "JSDocPropertyTag"
        | SyntaxKind.JSDocThrowsTag -> "JSDocThrowsTag"
        | SyntaxKind.JSDocSatisfiesTag -> "JSDocSatisfiesTag"
        | SyntaxKind.SyntaxList -> "SyntaxList"
        | SyntaxKind.NotEmittedStatement -> "NotEmittedStatement"
        | SyntaxKind.PartiallyEmittedExpression -> "PartiallyEmittedExpression"
        | SyntaxKind.CommaListExpression -> "CommaListExpression"
        | SyntaxKind.SyntheticReferenceExpression ->
            "SyntheticReferenceExpression"
        | SyntaxKind.Count -> "Count"
        | x -> string x
