name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests suite

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 10

    - name: Tests
      run: ./build.sh test

  lint:
    runs-on: ubuntu-latest
    name: Check formatting

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Check formatting
      run: ./build.sh lint
